name: ip_geolocation_api

services:
  postgres:
    image: postgres:17.4-alpine3.21
    container_name: geolocation_db
    restart: always
    env_file: ./ip_geolocation/.env
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin_container
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@example.com
#      PGADMIN_DEFAULT_PASSWORD: password
#    ports:
#      - "5050:80"

  django:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./ip_geolocation:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python -u manage.py runserver 0.0.0.0:8000
      "

volumes:
  pg_data: